name: "CodeQL"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: '92.118.113.35'
          username: 'root'
          password: 'uR6@9FiVfeB#2e'
          port: '22'
          script: |
            cd /var/www/projects/
            git pull 
            systemctl restart shop_drf.service
