name: "CodeQL"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh-key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 92.118.113.35
          username: root
          password: uR6@9FiVfeB#2e
          key: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAhV8380WWl94drG6qtHOtUhyuZRPJjgDlYEVofd2GlW3Xtz0AbsLi
9gmQrklH8GlGsjkgN0uM83UcEMHRXB/iCKTuA4umBmvtPb4znb801dLKRdrAUw2bftucmm
OSeFhon8iWkenJ7Wl4g6KLMyo2YpZq1hT3iQpEuA/tzVq8vBkti7VXQ85xJJxvynNpP2Y4
ojQ6MM0RkywjFQ2XMxv+9wra16Xnm45gcKBkZuxapFxqp6G1axEK7BqcsgIT54CEBAEk7Z
4I3ovbOdOEwPCv3tk5ch4OG4NAP/OVKTgFq0CP6FIBzHSsv6U6PSGTmVR5yXhXCOrsl+m7
jhV2oV4wzDuw4u4hMTZIVvn4orBg3LqN1/bhdEo7XnBk0Bss66TCV3Vgz0WUUHNFbzlfzA
mJ8N/g27U544IoIiumascD/h0fMutIlpTMyfnhvvATptYLXb3wJulaUIXpvHOr6X/KDw88
DWBg7XNE3bipKNB2HpALxqWJswZXgcALFbIElmabAAAFmAjdM5MI3TOTAAAAB3NzaC1yc2
EAAAGBAIVfN/NFlpfeHaxuqrRzrVIcrmUTyY4A5WBFaH3dhpVt17c9AG7C4vYJkK5JR/Bp
RrI5IDdLjPN1HBDB0Vwf4gik7gOLpgZr7T2+M52/NNXSykXawFMNm37bnJpjknhYaJ/Ilp
Hpye1peIOiizMqNmKWatYU94kKRLgP7c1avLwZLYu1V0POcSScb8pzaT9mOKI0OjDNEZMs
IxUNlzMb/vcK2tel55uOYHCgZGbsWqRcaqehtWsRCuwanLICE+eAhAQBJO2eCN6L2znThM
Dwr97ZOXIeDhuDQD/zlSk4BatAj+hSAcx0rL+lOj0hk5lUecl4Vwjq7Jfpu44VdqFeMMw7
sOLuITE2SFb5+KKwYNy6jdf24XRKO15wZNAbLOukwld1YM9FlFBzRW85X8wJifDf4Nu1Oe
OCKCIrpmrHA/4dHzLrSJaUzMn54b7wE6bWC1298CbpWlCF6bxzq+l/yg8PPA1gYO1zRN24
qSjQdh6QC8alibMGV4HACxWyBJZmmwAAAAMBAAEAAAGAEy+tTlSdQy/48n8hv9TWQvY3oP
h1lHU3ih+3Vkf3Hj76Jco46jYkopf3VW3a/frpvdDEUYAPq6RAtdO+qPM4jTLLafzTFPW+
CsBLukPb4hixRYGgYjJBGMDsqInDc9w6rNBqggdw/N4hL+/to3N39bsawmera8OWOtOmdi
tj9DvmVpnvOaS/QluIz3BxMbrO/IfpM8UEZA4Y5o9DyDPyUUVL/HLJkedWTfgc3sYzN0Ae
OGA7HMcLsbHAXJvk6Mw5ZxP5Iz0msMO+oGvLkCqh72Vid+SQz6Okxu8llaUZUSMuOtuIzH
UVq5isAxSWeTNd4zI7TwQeHgHB/udjbMzYDLjir04PHxD3KdGksmYYlJXxjZDZGoo4Jh2v
QiDnhNONloexO0dmFtjAzrxlHLmAztl1vlEDvKtOw0CFE2iL5JpHEXACNTsXneRFBBh+Np
vgKleeW0/8qNLqdBrRUBuX+fA8s4b5gJE62u7gq9+6iQJFPNmyTcz5so4WgnO0x/yxAAAA
wD2fx7IyP3zVloUi7WotWj9XRhc9CAFvSwq60qeZQdnnvVEmbNdjz2kSfavGap0Xj0PmZH
5qQHoFzHcYtPBv27946hJTN0ut5y8kr0zYR+qM5dV2V6n39XAkJubwO8b9yiSWE1IxFmjz
iM1Mm+VF6g9/f+p0MQhsvqtEpGRusw9LEyva8N7SVFFHiTpwQut3evBPwH5JZlOnv2oc/C
SyE+PRaYaOC4jLx52sBHpgN4293VWwL60o/JoJlLOUziSvegAAAMEAuudfJammuSSJ2VWl
/488d7SXajxDXJgmdKEqsWfyCs+FJqV1YsSoCCQHgs1+iCN7t0cL9n+nCNX0o/9xTDTJaC
lAlvjMOx7DWH4kpgITdn5tgF4C8duZYOUhvmowLsdtGtVYyEufG27BM4WUxo1+Gbt3GCAq
JrhaBNF62eSmQnVTxGOmv1I7yixlFokdEA9PM43z0rA648c0EewhZQS7zJ7yQhzSuWCQD3
zxm6id1Yj+y659hlpxk1B4kdxk9GILAAAAwQC2rZPbnXUbLW8NJUzHSSnjXxI9fc1ddMR4
iX30115TEmWm/i+qT9deriuyfxZxtEvId5kx/wZOPgYCswzqv5TGw4FrxEfkeKjyYzHcTR
658uqWNiuOdPxyvA0rcAlJF9Qo4/CmFGHFDctbok9rWSqgqQUbY+Avunu4R1ksJTucRS+k
FXFR4dqSjG8RCdvMlC5af+gxIZzszKsKGS+3vqlVRd7Xmt8qVjLhSxeYleRZPljQCXLyUw
UTZvxJUADS97EAAAAdcm9vdEAzNDY3NTMzLXRyMzM5MTEudHdjMS5uZXQBAgMEBQY=
-----END OPENSSH PRIVATE KEY-----"


          script: |
            cd /var/www/projects/
            git pull 
            systemctl restart shop_drf.service
